name: TURTLE QUAD V2
chassis:
  width: 0.07183850 # m
  length: 0.31559532 # m
leg:
  shoulderLen: 0.04715084 # m
  upperLen: 0.192 # m
  lowerLen: 0.192 # m
  footRadius: 0.020 # m
servomap:
  1: [11,12,13]
  2: [21,22,23]
  3: [31,32,33]
  4: [41,42,43]
  5: [1]