name: TURTLE QUAD V2
chassis:
  width: 0.07183850 # m
  length: 0.31559532 # m
leg:
  shoulderLen: 0.04715084 # m
  upperLen: 0.192 # m
  lowerLen: 0.192 # m
  footRadius: 0.020 # m
  lowerMin: 0.099
  lowerMax: 0.417
servomap:
  1: [11,12,13]
  2: [21,22,23]
  3: [31,32,33]
  4: [41,42,43]
  5: [1]
motor_config:
  - servopos.position_max nan
  - servopos.position_min nan
  - servo.pid_position.kp 100.0
  - servo.pid_position.ki 10.0
  - servo.pid_position.kd 10.0
  - servo.pid_position.ilimit 20.0
  - servo.max_velocity 10.0
  - servo.default_velocity_limit 8.0
  - servo.default_accel_limit 20.0
  - motor_position.rotor_to_output_ratio 0.0526315789
gamepad: /dev/input/by-id/usb-Logitech_Wireless_Gamepad_F710_D63B91BB-event-joystick